In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [6]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [8]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [9]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [14]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [17]:
df.fillna(8)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  8.0
2  8.0  3  3.0  8.0
3  4.0  4  8.0  8.0
4  5.0  5  8.0  5.0

In [20]:
val = {'A':100, 'B':5, 'C':600, 'D':88}
df.fillna(value=val)

       A  B      C     D
0    1.0  1    1.0   1.0
1    2.0  2    2.0  88.0
2  100.0  3    3.0  88.0
3    4.0  4  600.0  88.0
4    5.0  5  600.0   5.0

In [21]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [22]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0